name: Lint-CSharp

on:
  push:
    branches: 
    - main
    - feature/*
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 3.1.x
    - name: Code Style
      run: |
        dotnet tool install -g dotnet-format
        dotnet format --check -v diag